### ISSUE TITLE
Build Process Update

### ISSUE THREAD

**Issue by evanplaice** [vanillawc/wc-datepicker#2]
Now that ESMTK now has lint, bundle, and minify capabilities, can I add it to this project? Using ESMTK should allow removing `minify.cmd` and `template_minifier.js`

It would add the following scripts to `package.json`
```json
{
    "lint": "esmtk lint",
    "minify": "esmtk minify dist/wc-datepicker.js dist/wc-datepicker.min.js"
}
```

Also, are the node-specific bundles still necessary? As of 14.x Node is ESM compatible.

**Comment by jutunen** [comment]
> Now that ESMTK now has lint, bundle, and minify capabilities, can I add it to this project? Using ESMTK should allow removing `minify.cmd` and `template_minifier.js`
> 

Current minify.cmd has a list of reserved words that can not be minified. That list must be obeyed. Otherwise the build will be broken.

> Also, are the node-specific bundles still necessary? As of 14.x Node is ESM compatible.

Yes they are. Node 14.x is not even on Long Term Support track yet. I would estimate, that 14.x will be the dominating node version within 1 - 2 years. For now it's way too early to get rid of node-specific bundles.

**Comment by evanplaice** [comment]
Not sure what you mean by the build being broken by minification. The minification I am using in all of the other web components is smart enough not to break anything.

As for Node. The 10.x is scheduled for EOL in November at the same time 12.x goes into LTS. ESM has already been fully backported to 12.x with the experimental warnings scheduled to be removed when it goes into LTS. 14.x shipped with ESM and no warnings.

Besides, the Node-specific bundles in this project don't contain any node-specific code.

---

Either way, it's your decision. If you do decide to switch, I can guarantee that no broken code will be published. If there's an issue, the changes will be rolled back.
