### ISSUE TITLE
wc-datepicker issue in IE11

### ISSUE THREAD

**Issue by poornima-wc** [vanillawc/wc-datepicker#3]
Hello,
I tried to use wc-datepicker and it works perfect in Chrome & Edge. But it does not work in IE11.
![image](https://user-images.githubusercontent.com/82676148/115070592-23b7ee00-9ec3-11eb-9716-10214d19d883.png)
I use the below 2 script tags,
![image](https://user-images.githubusercontent.com/82676148/115070660-3c280880-9ec3-11eb-8e5a-5c76615d8b1e.png)
Please help.

Thanks.

**Comment by poornima-wc** [comment]
@jutunen @evanplaice please suggest

**Comment by evanplaice** [comment]
Standard web components are not -- and never will be -- supported in IE11

You could try using a 'web component' polyfill but I can't guarantee that this will still work as expected if you do
